# Copyright (c) 2020-2022 MeteoSwiss, contributors listed in AUTHORS.
#
# Distributed under the terms of the GNU General Public License v3.0 or later.
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This file contains a list of the different GRUAN Data Products (GDPs) supported by dvas.
# It must absolutely have the string 'model' in its name, to match the dvas class names.
# --------------------------------------------------------------------------------------------------

# Legend:
# mdl_name: model name used in the netCDF GDP filenames
# mdl_desc: free text description of the model
# mid: model id used by dvas

- mdl_name: 'RS41-GDP_001'
  mdl_desc: 'RS41 GDP, version 1'
  mid: '(gdp)RS41'

- mdl_name: 'RS92-GDP_002'
  mdl_desc: 'RS92 GDP, version 2'
  mid: '(gdp)RS92'

- mdl_name: 'IMS-100-BETA_002'
  mdl_desc: 'iMS-100 GDP, BETA version 2'
  mid: '(gdp)iMS-100'
