# ----------------------------------------------------
# M10 type (NOT THE GDP!)
# ----------------------------------------------------
_M10:

    # -- META DATA ----------------------------------
    edt: "get('event_dt')"
    srn: "get('srn')"
    pid: "get('product_id')"
    tags:
        - "cat('e:', get('event_id'))"
        - "cat('r:', get('rig'))"
        - "get('day_night')"
    metadata:
        has_descent:

    # -- ORIG DATA ----------------------------------
    csv_delimiter:
    csv_skip_blank_lines: False
    csv_delim_whitespace: True
    csv_skiprows: 0
    csv_skipfooter: 0
    csv_encoding:
    csv_na_values:
    csv_header: 0

    _time:
        value: get('Time', 'rel') # this is the number of seconds since 1970-01-01T00:00:00Z

    _alt_ref:
        value: get('Altitude')

    _gph:
        value: get('Altitude')

    _temp:
        value: get('T', 'd2k')

    _pres:
        value: get('Press')

    _rh:
        value: get('U')

    _wdir:
        value: get('WindD')

    _wspeed:
        value: get('WindF')

# ----------------------------------------------------
# M10 GDP, version alpha-2
# ----------------------------------------------------
_M10-GDP-ALPHA_002:

    # -- META DATA ----------------------------------
    edt: "get('g.Measurement.StandardTime')"
    srn: "get('g.MainSonde.SerialNumber')"
    pid: "get('g.Product.Id')"
    tags:
        - "cat('e:', get('g.Measurement.Id'))"
        - "cat('r:', get('g.Measurement.BalloonNumber'))"
    metadata:
        has_descent:

    # -- ORIG DATA ----------------------------------
    _time:
        value: get('time', 'rel')  # this is the number of seconds since 1970-01-01T00:00:00Z

    _alt_ref:
        value: get('alt_gph')

    _gph:
        value: get('alt_gph')

    _gph_uct:
        value: get('alt_gph_uc', 'div2')  # Go from K=2 to K=1

    #TODO:
    # alt_gph_uc_noise -> ucu ?
    # sqrt(alt_gph_uc_repe**2 + alt_gph_uc_manuf**2) -> uct ?

    #_gph_ucu:
    #    value: 'alt_gph_uc_ucor'

    _temp:
        value: get('temp')

    #_temp_ucr:
    #    value: 'temp_uc_ucor'

    #_temp_ucs:
    #    value: 'temp_uc_scor'

    _temp_uct:
        value: get('temp_uc', 'div2')  # Go from K=2 to K=1

    #_temp_flag:
    #    value: 0
    #    csv_use_default: True

    _pres:
        value: get('press_gnss')

    #TODO:
    _pres_uct:
        value: get('press_uc', 'div2')  # Go from K=2 to K=1

    #TODO: is this assignment correct ?
    #_pres_ucu:
    #    value: get('press_gnss_uc_noise', 'div2')  # Go from K=2 to K=1

    _rh:
        value: get('rh')

    #_rh_ucr:
    #    value: 'rh_uc_ucor'

    _rh_uct:
        value: get('rh_uc', 'div2')  # Go from K=2 to K=1

    _wdir:
        value: get('wdir')

    _wdir_ucu:
        value: get('wdir_uc', 'div2')  # Go from K=2 to K=1

    _wspeed:
        value: get('wspeed')

    _wspeed_ucu:
        value: get('wspeed_uc', 'div2')  # Go from K=2 to K=1
