# ----------------------------------------------------
# RS-92 type (NOT THE GDP!)
# ----------------------------------------------------
_RS92:

    # -- META DATA ----------------------------------
    edt: "get('event_dt')"
    srn: "get('srn')"
    pid: "get('product_id')"
    tags:
        - "cat('e:', get('event_id'))"
        - "cat('r:', get('rig'))"
        - "get('day_night')"
    metadata:
        key_str: '1'
        key_num: 1

    # -- ORIG DATA ----------------------------------
    csv_delimiter:
    csv_skip_blank_lines: True
    csv_delim_whitespace: True
    csv_skiprows: 1
    csv_skipfooter: 0
    csv_encoding:
    csv_na_values:
    csv_header: 0

    _time:
        value: get('Time', 's2ns')

    _alt_ref:
        value: get('Height')

    _gph:
        value: get('Height')

    _temp:
        value: get('T', 'd2k')

    _temp_flag:
        value: get(0)
        csv_use_default: True

    _pres:
        value: get('P')

    _rh:
        value: get('U')

    _wdir:
        value: get('WD')

    _wspeed:
        value: get('WS')

# ----------------------------------------------------
# RS92-GDP, version 2
# ----------------------------------------------------
_RS92-GDP_002:

    # -- META DATA ----------------------------------
    edt: "cat(get('g.Ascent.StandardTime'),'Z')"
    srn: "get('g.Instrument.SerialNumber')"
    pid: "get('g.Product.ID')"
    tags:
        - "cat('e:', get('g.Ascent.ID'))"
        - "cat('r:', get('g.Ascent.BalloonNumber'))"

    # -- ORIG DATA ----------------------------------
    _time:
        value: get('time', 's2ns')

    _alt_ref:
        value: get('geopot')

    _gph:
        value: get('geopot')

    _temp:
        value: get('temp')

    _temp_ucr:
        # In v2 of the GDP, this value is wrong. It must be reconstructed from:
        # value: sqrt('u_temp'**2 - 'u_cor_temp'**2)
        # See GRUAN TD4, section 5.1 for details.
        value: >-
            sqrt(sub(pow(get('u_temp'), 2), pow(get('u_cor_temp'), 2)))

    _temp_uct:
        value: get('u_cor_temp')

    _pres:
        value: get('press')

    _pres_uct:
        value: get('u_press')

    _rh:
        value: mul(get('rh'), 100) # Convert to %

    _rh_ucr:
        # In v2 of the GDP, this value is wrong. It must be reconstructed from:
        # value: sqrt('u_rh'**2 - 'u_cor_rh'**2)
        # See GRUAN TD4, section 5.1 for details.
        # Also, convert this to %
        value: >-
            mul(sqrt(sub(pow(get('u_rh'), 2), pow(get('u_cor_rh'), 2))), 100)

    _rh_uct:
        value: mul(get('u_cor_rh'), 100) # Convert to %

    _wdir:
        value: get('wdir')

    _wdir_ucu:
        value: get('u_wdir')

    _wspeed:
        value: get('wspeed')

    _wspeed_ucu:
        value: get('u_wspeed')
