# ----------------------------------------------------
# SRS-C34 type (NOT THE GDP!)
# ----------------------------------------------------
_C34:

    # -- META DATA ----------------------------------
    edt: "get('event_dt')"
    srn: "get('srn')"
    pid: "get('product_id')"
    tags:
        - "cat('e:', get('event_id'))"
        - "cat('r:', get('rig'))"
        - "get('day_night')"

    # -- ORIG DATA ----------------------------------
    csv_delimiter: ';'
    csv_skip_blank_lines: False
    csv_delim_whitespace: False
    csv_skiprows: 45
    csv_skipfooter: 1
    csv_encoding:
    csv_na_values:
    csv_header: 0

    _time:
        value: get('Rel. Time')

    _alt_ref:
        value: get('Altitude (gpm)')

    _gph:
        value: get('Altitude (gpm)')

    _temp:
        value: get('Temperature (?C)', 'd2k')

    _rh:
        value: get('Humidity (%)')

    _pres:
        value: get('Pressure (hPa)')

    _wdir:
        value: get('Wind Direction (?)')

    _wspeed:
        value: get('Wind Velocity (m/s)')
