# ----------------------------------------------------
# M10 type (NOT THE GDP!)
# ----------------------------------------------------
_M10:

    # -- META DATA ----------------------------------
    edt: "get('event_dt')"
    srn: "get('srn')"
    pid: "get('product_id')"
    tags:
        - "cat('e:', get('event_id'))"
        - "cat('r:', get('rig'))"
        - "get('day_night')"

    # -- ORIG DATA ----------------------------------
    csv_delimiter:
    csv_skip_blank_lines: True
    csv_delim_whitespace: True
    csv_skiprows: 1

    _time:
        value: get(0, 's2ns')

    _gph:
        value: get(1)

    _temp:
        value: get(10, 'd2k')

    _pres:
        value: get(12)

    _rh:
        value: get(11)

# ----------------------------------------------------
# M10 GDP, version alpha-1
# ----------------------------------------------------
_M10-GDP-ALPHA_001:

    # -- META DATA ----------------------------------
    edt: "get('g.Measurement.StandardTime')"
    srn: "get('g.MainSonde.SerialNumber')"
    pid: "get('g.Product.Id')"
    tags:
        - "cat('e:', get('g.Measurement.Id'))"
        - "cat('r:', get('g.Measurement.BalloonNumber'))"

    # -- ORIG DATA ----------------------------------
    _time:
        value: get('time', ['rel', 's2ns'])  # this is the number of seconds since 1970-01-01T00:00:00Z
        value: wcomp(get(1), get(10), 'N')
    _gph:
        value: get('alt_gph')

    _gph_uct:
        value: get('alt_gph_uc', 'div2')  # Go from K=2 to K=1

    #TODO:
    # alt_gph_uc_noise -> ucu ?
    # sqrt(alt_gph_uc_repe**2 + alt_gph_uc_manuf**2) -> uct ?

    #_gph_ucu:
    #    value: 'alt_gph_uc_ucor'

    _temp:
        value: get('temp')

    #_temp_ucr:
    #    value: 'temp_uc_ucor'

    #_temp_ucs:
    #    value: 'temp_uc_scor'

    _temp_uct:
        value: get('temp_uc', 'div2')  # Go from K=2 to K=1

    #_temp_flag:
    #    value: 0
    #    csv_use_default: True

    _pres:
        value: get('press_gnss')

    #TODO: is this assignment correct ?
    _pres_uct:
        value: get('press_gnss_uc_repe', 'div2')  # Go from K=2 to K=1

    #TODO: is this assignment correct ?
    _pres_ucu:
        value: get('press_gnss_uc_noise', 'div2')  # Go from K=2 to K=1

    _rh:
        value: get('rh')

    #_rh_ucr:
    #    value: 'rh_uc_ucor'

    _rh_uct:
        value: get('rh_uc', 'div2')  # Go from K=2 to K=1

    _wdir:
        value: get('wdir')

    _wdir_ucu:
        value: get('wdir_uc', 'div2')  # Go from K=2 to K=1

    _wspeed:
        value: get('wspeed')

    _wspeed_ucu:
        value: get('wspeed_uc', 'div2')  # Go from K=2 to K=1
