
- mdl_name: 'RS92'
  mdl_desc: 'Vaisala RS-92'
  mid: 'RS92'

- mdl_name: 'RS41'
  mdl_desc: 'Vaisala RS-41 SG'
  mid: 'RS41'

- mdl_name: 'C34'
  mdl_desc: 'Meteolabor SRS-C34'
  mid: 'C34'

- mdl_name: 'C50'
  mdl_desc: 'Meteolabor SRS-C50'
  mid: 'C50'
