
_RS92-GDP_002:

    dt_field: '$g.Ascent.StandardTime$Z'
    sn_field: '$g.Instrument.SerialNumber$'
    tag_field:
        - 'gdp'
        - 'b$g.Ascent.BalloonNumber$'
        - 'e$g.Ascent.ID$'

    time_field: 'time'

    _trepros1:
        param_field: 'temp'
        lambda: 'lambda x: x - 273.15'

    _treprosu:
        param_field: 'u_temp'

    _prepros1:
        param_field: 'press'


_RS41-GDP-BETA_001:

    dt_field: '$g.Measurement.StandardTime$'
    sn_field: '$g.MainSonde.SerialNumber$'
    tag_field:
        - 'gdp'
        - 'b$g.Measurement.BalloonNumber$'
        - 'e$g.Measurement.Id$'

    time_field: 'time'

    _trepros1:
        param_field: 'temp'
        lambda: 'lambda x: x - 273.15'
