blank_issues_enabled: true
contact_links:
  - name: Questions - Comments - Suggestions
    url: https://github.com/MCH-MDA/dvas/discussions
    about: Please ask questions, make comments, and submit suggestions here.
