
# ----------------------------------------------------
# RS-92 type for pseudo data (NOT THE GDP!)
# ----------------------------------------------------
_RS92:

    # -- META DATA ----------------------------------
    dt_field: '{event_dt}'
    srn_field: '{sn}'
    tag_field:
        - 'e:{event_id}'
        - 'r:{rig}'
        - '{day_night}'

    # -- ORIG DATA ----------------------------------
    csv_delimiter: ','
    csv_skipinitialspace: True

    _tdtpros1:
        value_col: 0
        lambda: 'lambda x: x * 1E9'

    _trepros1:
        value_col: 2

    _altpros1:
        value_col: 9

    _prepros1:
        value_col: 1

# ----------------------------------------------------
# YT type
# ----------------------------------------------------
_YT:

    # -- META DATA ----------------------------------
    dt_field: '{event_dt}Z'
    srn_field: '{sn}'
    tag_field:
        - 'e:{event_id}'
        - 'r:{rig}'
        - '{day_night}'

    # -- ORIG DATA ----------------------------------
    csv_delimiter: ','
    csv_skipinitialspace: True

    _tdtpros1:
        value_col: 0
        lambda: 'lambda x: x * 1E9'

    _trepros1:
        value_col: 1

    _altpros1:
        value_col: 2

    _prepros1:
        value_col: 3

# ----------------------------------------------------
# ZT type
# ----------------------------------------------------
_ZT:

    # -- META DATA ----------------------------------
    dt_field: '{event_dt}'
    srn_field: '{sn}'
    tag_field:
        - 'e:{event_id}'
        - 'r:{rig}'
        - '{day_night}'

    # -- ORIG DATA ----------------------------------
    csv_delimiter: ';'
    csv_skip_blank_lines: True

    _tdtpros1:
        value_col: 0
        lambda: 'lambda x: x * 1E9'

    _trepros1:
        value_col: 1

    _altpros1:
        value_col: 2

    _prepros1:
        value_col: 3

