
- tag_abbr: 'e([1-9]\d{0,1})'
  # Generate e1, e2, ..., e99
  tag_desc: 'Event $\1$'
  # Use standard re.sub group syntax to refer group number from regexp
  # generator.

- tag_abbr: 'r([12])'
  # Generate r1, r2
  tag_desc: 'Rig $\1$'

- tag_abbr: '^((day)|(night))'
  # Generate day, night
  # In this example, '^' is required at the beginning to
  # create regexp groups almost no group will be catch.
  tag_desc: '$lambda x: x.group(1)[0].upper() + x.group(1)[1:].lower()$ event'
  # Use lambda function to set 1st character to upper case and append the rest
  # of the group in lower case.
