# Copyright (c) 2020-2022 MeteoSwiss, contributors listed in AUTHORS.
#
# Distributed under the terms of the GNU General Public License v3.0 or later.
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This file contains the list of flags defined manually by the user.
# It must absolutely have the string 'flg' in its name, to match the dvas class names.
# --------------------------------------------------------------------------------------------------

# Legend:
# - bit_pos: bit position to store the flag, as int in the range [10, 62]. Some bits may be reserved
#   flg_name: short-and-sweet flag name for use in dvas
#   flg_desc: long(er) free text description of the flag

- bit_pos: 10
  flg_name: 'planetary_boundary_layer'
  flg_desc: 'Inside the planetery boundary layer'

- bit_pos: 11
  flg_name: 'troposphere'
  flg_desc: 'Below the tropopause (i.e. the PBL is included)'

- bit_pos: 12
  flg_name: 'free_troposphere'
  flg_desc: 'Above the PBL and below the tropopause'

- bit_pos: 13
  flg_name: 'stratosphere'
  flg_desc: 'Above the tropopause'

- bit_pos: 14
  flg_name: 'upper_troposphere_lower_startosphere'
  flg_desc: 'TBD'
