# Parameter configuration file
- prm_name: 'time'
  prm_desc: 'Time'
  prm_unit: 's'

- prm_name: 'alt_ref'
  prm_desc: 'Reference altitude'
  prm_unit: 'm'

- prm_name: 'gph(|(_uct)|(_ucu))'
  # Generate variables from regex generator for geopotential height.
  prm_desc: 'cat("Geopotential height", repl({"_uct": " temporal-correlated uncertainty",
                                              "_ucu": " un-correlated uncertainty"}, get(1)))'
  prm_unit: 'm'

- prm_name: 'temp(|(_ucr)|(_ucs)|(_uct)|(_ucu))'
  # Generate variables from regex generator for temperature.
  prm_desc: 'cat("Temperature", repl({"_ucr": " rig-correlated uncertainty",
                                      "_ucs": " spatial-correlated uncertainty",
                                      "_uct": " temporal-correlated uncertainty",
                                      "_ucu": " un-correlated uncertainty"}, get(1)))'
  prm_unit: 'K'

- prm_name: 'rh(|(_ucr)|(_uct)|(_ucu))'
  # Generate variables from regex generator for relative humidity.
  prm_desc: 'cat("Relative humidity", repl({"_ucr": " rig-correlated uncertainty",
                                            "_uct": " temporal-correlated uncertainty",
                                            "_ucu": " un-correlated uncertainty"}, get(1)))'
  prm_unit: '%'

- prm_name: '(pres|alt)(|(_uct))'
  # Generate variables from regex generator for pressure, altitude AMSL, and geopotential height.
  prm_desc: 'cat(repl({"pres": "Pressure",
                        "alt": "Altitude a.m.s.l."}, get(1)),
                 repl({"_uct": " temporal-correlated uncertainty"}, get(2)))'
  prm_unit: 'repl({"pres": "hPa",
                    "alt": "m"}, get(1))'

- prm_name: '(wdir|wspeed)(|(_ucu))'
  # Generate variables from regex generator for wind direction and wind speed.
  prm_desc: 'cat(repl({"wdir": "Wind direction",
                        "wspeed": "Wind speed"}, get(1)),
                 repl({"_ucu": " un-correlated uncertainty"}, get(2)))'
  prm_unit: 'repl({"wdir": "deg",
                    "wspeed": "m/s"}, get(1))'
