"""
This module contains the required attributes definition for
.config.ConfigManager.InstrType which is a .config.ConfigManager child.

Created February 2020, L. Modolo - mol@meteoswiss.ch

"""

# Import current packages modules
from ...database.model import Flag

# Define
RAWNA_ABBR = 'raw_na'
RESMPL_ABBR = 're_smpl'
UPSMPL_ABBR = 'up_smpl'
INTERP_ABBR = 'interp'
SYNC_ABBR = 'sync'
AUTOQC_ABBR = 'auto_qc'

#: dict: Parameter pattern properties (JSON_SCHEMA)
PARAMETER_PATTERN_PROP = {
    rf"^{Flag.bit_number.name}$": {
        "type": "integer",
        "minimum": 6,
    },
    rf"^{Flag.flag_abbr.name}$": {
        "type": "string"
    },
    rf"^{Flag.flag_desc.name}$": {
        "type": "string"
    }
}

#: list: Constant node values
CONST_NODES = [
    {
        Flag.bit_number.name: 0,
        Flag.flag_abbr.name: RAWNA_ABBR,
        Flag.flag_desc.name: "Raw NA"
    },
    {
        Flag.bit_number.name: 1,
        Flag.flag_abbr.name: RESMPL_ABBR,
        Flag.flag_desc.name: "Resampled"
    },
    {
        Flag.bit_number.name: 2,
        Flag.flag_abbr.name: UPSMPL_ABBR,
        Flag.flag_desc.name: "Resampled"
    },
    {
        Flag.bit_number.name: 3,
        Flag.flag_abbr.name: INTERP_ABBR,
        Flag.flag_desc.name: 'Interpolated'
    },
    {
        Flag.bit_number.name: 4,
        Flag.flag_abbr.name: SYNC_ABBR,
        Flag.flag_desc.name: 'Synchronized'
    },
    {
        Flag.bit_number.name: 5,
        Flag.flag_abbr.name: AUTOQC_ABBR,
        Flag.flag_desc.name: 'Auto QC flagged'
    },
]

#: str: Config manager key name
KEY = Flag.__name__

#: str: Node name able to be generated by regexp
NODE_GEN = ''
