"""
Copyright (c) 2020-2021 MeteoSwiss, contributors listed in AUTHORS.

Distributed under the terms of the GNU General Public License v3.0 or later.

SPDX-License-Identifier: GPL-3.0-or-later

Module contents: Required attributes definition for `.config.ConfigManager.Flag class`.

"""

# Import current packages modules
from ...database.model import Flag as TableFlag

#: dict: Parameter pattern properties (JSON_SCHEMA)
PARAMETER_PATTERN_PROP = {
    rf"^{TableFlag.bit_pos.name}$": {
        "type": "integer",
        "minimum": 10,
    },
    rf"^{TableFlag.flag_name.name}$": {
        "type": "string"
    },
    rf"^{TableFlag.flag_desc.name}$": {
        "type": "string"
    }
}

#: list: Constant node values
CONST_NODES = [
    {
        TableFlag.bit_pos.name: 0,
        TableFlag.flag_name.name: 'raw_na',
        TableFlag.flag_desc.name: "Raw NA data"
    },
    {
        TableFlag.bit_pos.name: 1,
        TableFlag.flag_name.name: 'resampled',
        TableFlag.flag_desc.name: "Resampled data"
    },
    {
        TableFlag.bit_pos.name: 2,
        TableFlag.flag_name.name: 'interp',
        TableFlag.flag_desc.name: "Interpolated data"
    },
    {
        TableFlag.bit_pos.name: 3,
        TableFlag.flag_name.name: 'day',
        TableFlag.flag_desc.name: "Day measurement point"
    },
    {
        TableFlag.bit_pos.name: 4,
        TableFlag.flag_name.name: 'night',
        TableFlag.flag_desc.name: "Night measurement point"
    },
]

#: str: Config manager key name
KEY = TableFlag.__name__

#: str: Node name able to be generated by regexp
NODE_GEN = ''
