"""
Copyright (c) 2020-2021 MeteoSwiss, contributors listed in AUTHORS.

Distributed under the terms of the GNU General Public License v3.0 or later.

SPDX-License-Identifier: GPL-3.0-or-later

Module contents: Required attributes definition for `.config.ConfigManager.Flag class`.

"""

# Import current packages modules
from ...database.model import Flag as TableFlag
from ...hardcoded import TAG_EMPTY_NAME, TAG_EMPTY_DESC
from ...hardcoded import TAG_INVALID_NAME, TAG_INVALID_DESC
from ...hardcoded import TAG_INTERP_NAME, TAG_INTERP_DESC

#: dict: Parameter pattern properties (JSON_SCHEMA)
PARAMETER_PATTERN_PROP = {
    rf"^{TableFlag.bit_pos.name}$": {
        "type": "integer",
        "minimum": 10,
        "maximum": 63,
    },
    rf"^{TableFlag.flag_name.name}$": {
        "type": "string"
    },
    rf"^{TableFlag.flag_desc.name}$": {
        "type": "string"
    }
}

#: list: Constant node values
CONST_NODES = [
    {
        TableFlag.bit_pos.name: i,
        TableFlag.flag_name.name: arg[0],
        TableFlag.flag_desc.name: arg[1]
    } for i, arg in enumerate(
        (
            (TAG_EMPTY_NAME, TAG_EMPTY_DESC),
            (TAG_INVALID_NAME, TAG_INVALID_DESC),
            (TAG_INTERP_NAME, TAG_INTERP_DESC),
        )
    )
]

#: str: Config manager key name
KEY = TableFlag.__name__

#: str: Node name able to be generated by regexp
NODE_GEN = ''
