"""
Copyright (c) 2020 MeteoSwiss, contributors listed in AUTHORS.

Distributed under the terms of the GNU General Public License v3.0 or later.

SPDX-License-Identifier: GPL-3.0-or-later

Module contents: Required attributes definition for
.config.ConfigManager.InstrType class.

"""

# Import current packages modules
from ..pattern import INSTR_TYPE_PAT
from ...database.model import InstrType as TableInstrType

#: list: Constant node values
CONST_NODES = [
    {
        TableInstrType.type_name.name: '',
        TableInstrType.type_desc.name: 'Null instrument type',
    }
]

#: dict: Parameter pattern properties (JSON_SCHEMA)
PARAMETER_PATTERN_PROP = {
    rf"^{TableInstrType.type_name.name}$": {
        "type": "string",
        "pattern": INSTR_TYPE_PAT,
    },
    rf"^{TableInstrType.type_desc.name}$": {
        "type": "string"
    }
}

#: str: Config manager key name
KEY = TableInstrType.__name__

#: str: Node name able to be generated by regexp
NODE_GEN = ''
