"""
Copyright(c) 2020 MeteoSwiss, contributors listed in AUTHORS

Distributed under the terms of the BSD 3 - Clause License.

SPDX - License - Identifier: BSD - 3 - Clause

Module contents: Required attributes definition for
.config.ConfigManager.InstrType class.

"""

# Import current packages modules
from ..pattern import INSTR_TYPE_PAT
from ...database.model import InstrType

#: list: Constant node values
CONST_NODES = [
    {
        InstrType.type_name.name: '',
        InstrType.desc.name: 'Null instrument type',
    }
]

#: dict: Parameter pattern properties (JSON_SCHEMA)
PARAMETER_PATTERN_PROP = {
    rf"^{InstrType.type_name.name}$": {
        "type": "string",
        "pattern": INSTR_TYPE_PAT,
    },
    rf"^{InstrType.desc.name}$": {
        "type": "string"
    }
}

#: str: Config manager key name
KEY = InstrType.__name__

#: str: Node name able to be generated by regexp
NODE_GEN = ''
