"""
Copyright (c) 2020 MeteoSwiss, contributors listed in AUTHORS.

Distributed under the terms of the GNU General Public License v3.0 or later.

SPDX-License-Identifier: GPL-3.0-or-later

Module contents: Required attributes definition for
.config.ConfigManager.Parameter class.

"""

# TODO
#  Define whether the creation of constant parameters can be useful

# Import current packages modules
from ...database.model import Parameter as TableParameter

#: dict: Parameter pattern properties (JSON_SCHEMA)
PARAMETER_PATTERN_PROP = {
    rf"^{TableParameter.prm_name.name}$": {
        "type": "string",
    },
    rf"^{TableParameter.prm_desc.name}$": {
        "type": "string"
    },
    rf"^{TableParameter.prm_unit.name}$": {
        "type": "string"
    }
}

#: str: Config manager key name
KEY = TableParameter.__name__

#: str: Node name able to be generated by regexp
NODE_GEN = TableParameter.prm_name.name
