"""
Copyright(c) 2020 MeteoSwiss, contributors listed in AUTHORS

Distributed under the terms of the BSD 3 - Clause License.

SPDX - License - Identifier: BSD - 3 - Clause

Module contents: Required attributes definition for
.config.ConfigManager.Parameter class.

"""

# Import current packages modules
from ...database.model import Parameter

#: dict: Parameter pattern properties (JSON_SCHEMA)
PARAMETER_PATTERN_PROP = {
    rf"^{Parameter.prm_abbr.name}$": {
        "type": "string",
    },
    rf"^{Parameter.prm_desc.name}$": {
        "type": "string"
    }
}

#: str: Config manager key name
KEY = Parameter.__name__

#: str: Node name able to be generated by regexp
NODE_GEN = Parameter.prm_abbr.name
