"""
This module contains the required attributes definition for
.config.ConfigManager.Tag which is a .config.ConfigManager child.

Created June 2020, L. Modolo - mol@meteoswiss.ch

"""

# Import current packages modules
from ...database.model import Tag

#: dict: Parameter pattern properties (JSON_SCHEMA)
PARAMETER_PATTERN_PROP = {
    rf"^{Tag.tag_abbr.name}$": {
        "type": "string",
    },
    rf"^{Tag.tag_desc.name}$": {
        "type": "string"
    },
}

CONST_NODES = [
    {
        Tag.tag_abbr.name: 'raw',
        Tag.tag_desc.name: 'Data are raw'
    },
    {
        Tag.tag_abbr.name: 'derived',
        Tag.tag_desc.name: 'Data are derived from raw'
    },
    {
        Tag.tag_abbr.name: 'resampled',
        Tag.tag_desc.name: 'Data are resampled'
    },
    {
        Tag.tag_abbr.name: 'sync',
        Tag.tag_desc.name: 'Data are synchronized'
    },
]

#: str: Config manager key name
KEY = Tag.__name__

#: str: Node name able to be generated by regexp
NODE_GEN = Tag.tag_abbr.name
