"""
Copyright(c) 2020 MeteoSwiss, contributors listed in AUTHORS

Distributed under the terms of the BSD 3 - Clause License.

SPDX - License - Identifier: BSD - 3 - Clause

Module contents: Required attributes definition for
.config.ConfigManager.Tag class.

"""

# Import current packages modules
from ...database.model import Tag

#: dict: Parameter pattern properties (JSON_SCHEMA)
PARAMETER_PATTERN_PROP = {
    rf"^{Tag.tag_abbr.name}$": {
        "type": "string",
    },
    rf"^{Tag.tag_desc.name}$": {
        "type": "string"
    },
}

#: list: Constant node values
CONST_NODES = [
    {
        Tag.tag_abbr.name: 'raw',
        Tag.tag_desc.name: 'Data are raw'
    },
    {
        Tag.tag_abbr.name: 'gdp',
        Tag.tag_desc.name: 'GRUAN Data Product'
    },
    {
        Tag.tag_abbr.name: 'derived',
        Tag.tag_desc.name: 'Data are derived from raw'
    },
    {
        Tag.tag_abbr.name: 'resampled',
        Tag.tag_desc.name: 'Data are resampled'
    },
    {
        Tag.tag_abbr.name: 'sync',
        Tag.tag_desc.name: 'Data are synchronized'
    },
]

#: str: Config manager key name
KEY = Tag.__name__

#: str: Node name able to be generated by regexp
NODE_GEN = Tag.tag_abbr.name
