# Copyright (c) 2020-2022 MeteoSwiss, contributors listed in AUTHORS.
#
# Distributed under the terms of the GNU General Public License v3.0 or later.
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This file contains a list of the different Manufacturer Data Products (MDPs) supported by dvas.
# It must absolutely have the string 'model' in its name, to match the dvas class names.
# --------------------------------------------------------------------------------------------------

# Legend:
# mdl_name: model name used in the csv filenames
# mdl_desc: free text description of the model
# mid: model id used by dvas

- mdl_name: 'C34'
  mdl_desc: 'Meteolabor SRS-C34'
  mid: 'C34'

- mdl_name: 'C50'
  mdl_desc: 'Meteolabor SRS-C50'
  mid: 'C50'

- mdl_name: 'RS92'
  mdl_desc: 'Vaisala RS92'
  mid: 'RS92'

- mdl_name: 'RS41-MCH-PRE2018'
  mdl_desc: 'Vaisala RS41-SG (MCH pre-2018 file format)'
  mid: 'RS41-MCH'

- mdl_name: 'RS41-MCH'
  mdl_desc: 'Vaisala RS41-SG (MCH current file format)'
  mid: 'RS41-MCH'

- mdl_name: 'M10'
  mdl_desc: 'MétéoModem M10'
  mid: 'M10'

# --------------- UAII 2022 MDPs ------------------------

- mdl_name: 'ATMS-3710'
  mdl_desc: 'ATMS-3710 from Azista Industries Pvt Ltd [UAII2022 file format]'
  mid: 'ATMS-3710'

- mdl_name: 'CF-06-AH'
  mdl_desc: 'CF-06-AH from Aerospace Newsky Technology Co., Ltd. [UAII2022 file format]'
  mid: 'CF-06-AH'

- mdl_name: 'DFM-17'
  mdl_desc: 'DFM-17 from Graw Radiosondes GmbH & Co. KG [UAII2022 file format]'
  mid: 'DFM-17'

- mdl_name: 'GTH3'
  mdl_desc: 'HT-GTS(U)2-1 (GTH3) from Tianjin Huayuntianyi Special Meteorological Sounding Tech Co., Ltd. [UAII2022 file format]'
  mid: 'GTH3'

- mdl_name: 'iMet-54'
  mdl_desc: 'iMet-54 from Diel Met Systems (Pty) Ltd trading as InterMet [UAII2022 file format]'
  mid: 'iMet-54'

- mdl_name: 'iMS-100'
  mdl_desc: 'Meisei iMS-100 GPS radiosonde from Meisei Electric co., ltd. [UAII2022 file format]'
  mid: 'iMS-100'

- mdl_name: 'M20'
  mdl_desc: 'Meteomodem-M20 from Meteomodem [UAII2022 file format]'
  mid: 'M20'

- mdl_name: 'PS-B3'
  mdl_desc: 'Pisharoty Sonde B3 from Vikram Sarabhai Space Center, Indian Space Research Organisation [UAII2022 file format]'
  mid: 'PS-B3'

- mdl_name: 'RS41'
  mdl_desc: 'RS41-SG from Vaisala [UAII2022 file format]'
  mid: 'RS41'

- mdl_name: 'WxR-301D'
  mdl_desc: 'WxR-301D from Weathex [UAII2022 file format]'
  mid: 'WxR-301D'
