# Copyright (c) 2020-2022 MeteoSwiss, contributors listed in AUTHORS.
#
# Distributed under the terms of the GNU General Public License v3.0 or later.
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This file contains a list of the different Manufacturer Data Products (MDPs) supported by dvas.
# It must absolutely have the string 'model' in its name, to match the dvas class names.
# --------------------------------------------------------------------------------------------------

# Legend:
# mdl_name: model name used in the csv filenames
# mdl_desc: free text description of the model
# mid: model id used by dvas

- mdl_name: 'C34'
  mdl_desc: 'Meteolabor SRS-C34'
  mid: 'C34'

- mdl_name: 'C50'
  mdl_desc: 'Meteolabor SRS-C50'
  mid: 'C50'

- mdl_name: 'RS92'
  mdl_desc: 'Vaisala RS92'
  mid: 'RS92'

- mdl_name: 'RS41-MCH-PRE2018'
  mdl_desc: 'Vaisala RS41-SG (MCH pre-2018 file format)'
  mid: 'RS41-MCH'

- mdl_name: 'RS41-MCH'
  mdl_desc: 'Vaisala RS41-SG (MCH current file format)'
  mid: 'RS41-MCH'

- mdl_name: 'M10'
  mdl_desc: 'MétéoModem M10'
  mid: 'M10'

# --------------- UAII 2022 MDPs ------------------------

- mdl_name: 'ATMS-3710'
  mdl_desc: 'Azista Industries Pvt Ltd. ATMS-3710 (UAII2022)'
  mid: 'ATMS-3710'

- mdl_name: 'DFM-17'
  mdl_desc: 'GRAW DFM-17 (UAII2022)'
  mid: 'DFM-17'

- mdl_name: 'iMet-54-AA'
  mdl_desc: 'InterMet iMet-54-AA (UAII2022)'
  mid: 'iMet-54-AA'

- mdl_name: 'PS01B3M'
  mdl_desc: 'VSSC PS01B3M (UAII2022)'
  mid: 'PS01B3M'

- mdl_name: 'HT03G-1U'
  mdl_desc: 'Tianjin Huayuntianyi Special Meteorological Sounding Tech Co. Ltd HT03G-1U(GTH3) (UAII2022)'
  mid: 'HT03G-1U'

- mdl_name: 'RS41-SG'
  mdl_desc: 'Vaisala RS41-SG (UAII2022)'
  mid: 'RS41-SG'
