# 2020.12.18 012:00:00
- srn: 'testM1453523'
  instr_type: 'RS92'

- srn: 'testM1453554'
  instr_type: 'RS92'

- srn: 'testM2710728'
  instr_type: 'RS41'

- srn: 'testM2710695'
  instr_type: 'RS41'

- srn: '6001'
  instr_type: 'C34'

- srn: '4677'
  instr_type: 'C34'

- srn: '761'
  instr_type: 'C50'

- srn: '1083'
  instr_type: 'C50'

