
# 2018.01.10 00:00:00
- sn: 'YT-100'
  instr_type: 'YT'

- sn: 'ZT-100'
  instr_type: 'ZT'

# 2018.01.25 12:00:00
- sn: 'YT-101'
  instr_type: 'YT'

- sn: 'ZT-101'
  instr_type: 'ZT'

# Totally fake example
- sn: '123456789'
  instr_type: 'ZT'
