# 2020-12-19 16:00:00

########################################
# MultiPayload Flight 20170712T000000  #
########################################
- srn: 'M1453523'
  instr_type: 'RS92-GDP_002'

- srn: 'M2710695'
  instr_type: 'RS41-GDP-BETA_001'


########################################
# MultiPayload Flight 20171024T120000  #
########################################
- srn: 'M1453554'
  instr_type: 'RS92-GDP_002'

- srn: 'M2710728'
  instr_type: 'RS41-GDP-BETA_001'