
# 2018.01.10 00:00:00
- sn: 'AR-000'
  instr_type: 'AR-GDP_001'

- sn: 'BR-000'
  instr_type: 'BR-GDP_001'


# 2018.01.25 00:00:00
- sn: 'AR-001'
  instr_type: 'AR-GDP_001'

- sn: 'BR-001'
  instr_type: 'BR-GDP_001'
