
# 2018.01.10 00:00:00
- srn: 'YT-100'
  instr_type: 'YT'

- srn: 'ZT-100'
  instr_type: 'ZT'

# 2018.01.25 12:00:00
- srn: 'YT-101'
  instr_type: 'YT'

- srn: 'ZT-101'
  instr_type: 'ZT'

# Totally fake example
- srn: '123456789'
  instr_type: 'ZT'
