# ----------------------------------------------------
# SRS-C50 type (NOT THE GDP!)
# ----------------------------------------------------
_C50:

    # -- META DATA ----------------------------------
    edt: "get('event_dt')"
    srn: "get('srn')"
    pid: "get('product_id')"
    tags:
        - "cat('e:', get('event_id'))"
        - "cat('r:', get('rig'))"
        - "get('day_night')"

    # -- ORIG DATA ----------------------------------
    csv_delimiter: ';'
    csv_skip_blank_lines: True
    csv_skiprows: 40
    csv_skipfooter: 1

    _time:
        value: get(0, 's2ns')

    _gph:
        value: get(1)

    _temp:
        value: get(5)

    _pres:
        value: get(4)


# ----------------------------------------------------
# SRS-C34 type (NOT THE GDP!)
# ----------------------------------------------------
_C34:

    # -- META DATA ----------------------------------

    edt: "get('event_dt')"
    srn: "get('srn')"
    pid: "get('product_id')"
    tags:
        - "cat('e:', get('event_id'))"
        - "cat('r:', get('rig'))"
        - "get('day_night')"

    # -- ORIG DATA ----------------------------------
    csv_delimiter: ';'
    csv_skip_blank_lines: True
    csv_skiprows: 48
    csv_skipfooter: 1

    _time:
        value: get(0, 's2ns')

    _gph:
        value: get(1)

    _temp:
        value: get(5)

    _pres:
        value: get(4)

# ----------------------------------------------------
# RS-41 type (NOT THE GDP!), pre-2018 file format
# ----------------------------------------------------
_RS41-PRE2018:

    # -- META DATA ----------------------------------
    edt: "get('event_dt')"
    srn: "get('srn')"
    pid: "get('product_id')"
    tags:
        - "cat('e:', get('event_id'))"
        - "cat('r:', get('rig'))"
        - "get('day_night')"

    # -- ORIG DATA ----------------------------------
    csv_delimiter:
    csv_skip_blank_lines: True
    csv_delim_whitespace: True
    csv_skiprows: 1

    _time:
        value: get(0, 's2ns')

    _gph:
        value: get(2)

    _temp:
        value: get(4, 'd2k')

    _pres:
        value: get(3)

    _rh:
        value: get(5)

# ----------------------------------------------------
# RS-41 type (NOT THE GDP!), latest file format
# ----------------------------------------------------
_RS41:

    # -- META DATA ----------------------------------
    edt: "get('event_dt')"
    srn: "get('srn')"
    pid: "get('product_id')"
    tags:
        - "cat('e:', get('event_id'))"
        - "cat('r:', get('rig'))"
        - "get('day_night')"

    # -- ORIG DATA ----------------------------------
    csv_delimiter: ';'
    csv_skip_blank_lines: True
    csv_delim_whitespace: False
    csv_skiprows: 47

    _time:
        value: get(0, 's2ns')

    _gph:
        value: get(2)

    _temp:
        value: get(4, 'd2k')

    _pres:
        value: get(3)

    _rh:
        value: get(5)

# ----------------------------------------------------
# RS-92 type (NOT THE GDP!)
# ----------------------------------------------------
_RS92:

    # -- META DATA ----------------------------------
    edt: "get('event_dt')"
    srn: "get('srn')"
    pid: "get('product_id')"
    tags:
        - "cat('e:', get('event_id'))"
        - "cat('r:', get('rig'))"
        - "get('day_night')"
    metadata:
        key_str: '1'
        key_num: 1

    # -- ORIG DATA ----------------------------------
    csv_delimiter:
    csv_skip_blank_lines: True
    csv_delim_whitespace: True
    csv_skiprows: 2

    _time:
        value: get(0, 's2ns')

    _gph:
        value: get(1)

    _temp:
        value: get(3, 'd2k')

    _temp_flag:
        value: get(0)
        csv_use_default: True

    _pres:
        value: get(2)

    _rh:
        value: get(4)

# ----------------------------------------------------
# M10 type (NOT THE GDP!)
# ----------------------------------------------------
_M10:

    # -- META DATA ----------------------------------
    edt: "get('event_dt')"
    srn: "get('srn')"
    pid: "get('product_id')"
    tags:
        - "cat('e:', get('event_id'))"
        - "cat('r:', get('rig'))"
        - "get('day_night')"

    # -- ORIG DATA ----------------------------------
    csv_delimiter:
    csv_skip_blank_lines: True
    csv_delim_whitespace: True
    csv_skiprows: 1

    _time:
        value: get(0, 's2ns')

    _gph:
        value: get(1)

    _temp:
        value: get(10, 'd2k')

    _pres:
        value: get(12)

    _rh:
        value: get(11)

# ----------------------------------------------------
# RS-41 GDP, version beta-1
# ----------------------------------------------------
_RS41-GDP-BETA_001:

    # -- META DATA ----------------------------------

    edt: "get('g.Measurement.StandardTime')"
    srn: "get('g.MainSonde.SerialNumber')"
    pid: "get('g.Product.ID')"
    tags:
        - "cat('e:', get('g.Measurement.Id'))"
        - "cat('r:', get('g.Measurement.BalloonNumber'))"

    # -- ORIG DATA ----------------------------------
    _time:
        value: get('time', 's2ns')

    _gph:
        value: get('alt_gph')

    _temp:
        value: get('temp')

    _temp_ucr:
        value: get('temp_uc_ncor', 'div2')  # Go from K=2 to K=1

    _temp_ucs:
        value: get('temp_uc_scor', 'div2')  # Go from K=2 to K=1

    _temp_uct:
        value: get('temp_uc_tcor', 'div2')  # Go from K=2 to K=1

    _temp_flag:
        value: get(0)
        csv_use_default: True

    _pres:
        value: get('press_gnss')

    _pres_uct:
        value: get('press_gnss_uc', 'div2')  # Go from K=2 to K=1

    _wdir:
        value: get('wdir')

    _wdir_ucu:
        value: get('wdir_uc', 'div2')  # Go from K=2 to K=1

    _wspeed:
        value: get('wspeed')

    _wspeed_ucu:
        value: get('wspeed_uc', 'div2')  # Go from K=2 to K=1

# ----------------------------------------------------
# RS-41 GDP, version beta-2
# ----------------------------------------------------
_RS41-GDP-BETA_002:

    # -- META DATA ----------------------------------

    edt: "get('g.Measurement.StandardTime')"
    srn: "get('g.MainSonde.SerialNumber')"
    pid: "get('g.Product.Id')"
    tags:
        - "cat('e:', get('g.Measurement.Id'))"
        - "cat('r:', get('g.Measurement.BalloonNumber'))"

    # -- ORIG DATA ----------------------------------
    _time:
        value: get('time', 's2ns')

    _gph:
        value: get('alt_gph')

    _gph_uct:
        value: get('alt_gph_uc_tcor', 'div2')  # Go from K=2 to K=1

    _gph_ucu:
        value: get('alt_gph_uc_ucor', 'div2')  # Go from K=2 to K=1

    _temp:
        value: get('temp')

    _temp_ucr:
        value: get('temp_uc_ucor', 'div2')  # Go from K=2 to K=1

    _temp_ucs:
        value: get('temp_uc_scor', 'div2')  # Go from K=2 to K=1

    _temp_uct:
        value: get('temp_uc_tcor', 'div2')  # Go from K=2 to K=1

    _temp_flag:
        value: get(0)
        csv_use_default: True

    _pres:
        value: get('press_gnss')

    _pres_uct:
        value: get('press_gnss_uc_tcor', 'div2')  # Go from K=2 to K=1

    _pres_ucu:
        value: get('press_gnss_uc_ucor', 'div2')  # Go from K=2 to K=1

    _rh:
        value: get('rh')

    _rh_ucr:
        value: get('rh_uc_ucor', 'div2')  # Go from K=2 to K=1

    _rh_uct:
        value: get('rh_uc_tcor', 'div2')  # Go from K=2 to K=1

    _wdir:
        value: get('wdir')

    _wdir_ucu:
        value: get('wdir_uc', 'div2')  # Go from K=2 to K=1

    _wspeed:
        value: get('wspeed')

    _wspeed_ucu:
        value: get('wspeed_uc', 'div2')  # Go from K=2 to K=1

# ----------------------------------------------------
# RS92-GDP, version 2
# ----------------------------------------------------
_RS92-GDP_002:

    # -- META DATA ----------------------------------
    edt: "cat(get('g.Ascent.StandardTime'),'Z')"
    srn: "get('g.Instrument.SerialNumber')"
    pid: "get('g.Product.ID')"
    tags:
        - "cat('e:', get('g.Ascent.ID'))"
        - "cat('r:', get('g.Ascent.BalloonNumber'))"

    # -- ORIG DATA ----------------------------------
    _time:
        value: get('time', 's2ns')

    _gph:
        value: get('geopot')

    _temp:
        value: get('temp')

    _temp_ucr:
        # In v2 of the GDP, this value is wrong. It must be reconstructed from:
        # value: sqrt('u_temp'**2 - 'u_cor_temp'**2)
        value: >-
            sqrt(
                sub(
                    pow(get('u_temp'), 2),
                    pow(get('u_cor_temp'), 2)
                )
            )

    _temp_uct:
        value: get('u_cor_temp')

    _pres:
        value: get('press')

    _pres_uct:
        value: get('u_press')

    _rh:
        value: get('rh')

    _rh_ucr:
        # TODO: this needs to be checked. Is it as wrong as the temperature ?
        value: get('u_std_rh')

    _rh_uct:
        value: get('u_cor_rh')

    _wdir:
        value: get('wdir')

    _wdir_ucu:
        value: get('u_wdir')

    _wspeed:
        value: get('wspeed')

    _wspeed_ucu:
        value: get('u_wspeed')

# ----------------------------------------------------
# M10 GDP, version alpha-1
# ----------------------------------------------------
_M10-GDP-ALPHA_001:

    # -- META DATA ----------------------------------
    edt: "get('g.Measurement.StandardTime')"
    srn: "get('g.MainSonde.SerialNumber')"
    pid: "get('g.Product.Id')"
    tags:
        #- "cat('e:', get('g.Measurement.Id'))"
        - "cat('r:', get('g.Measurement.BalloonNumber'))"

    # -- ORIG DATA ----------------------------------
    _time:
        value: get('time', ['rel', 's2ns'])  # this is the number of seconds since 1970-01-01T00:00:00Z

    _gph:
        value: get('alt_gph')

    _gph_uct:
        value: get('alt_gph_uc', 'div2')  # Go from K=2 to K=1

    #TODO:
    # alt_gph_uc_noise -> ucu ?
    # sqrt(alt_gph_uc_repe**2 + alt_gph_uc_manuf**2) -> uct ?

    #_gph_ucu:
    #    value: 'alt_gph_uc_ucor'

    _temp:
        value: get('temp')

    #_temp_ucr:
    #    value: 'temp_uc_ucor'

    #_temp_ucs:
    #    value: 'temp_uc_scor'

    _temp_uct:
        value: get('temp_uc', 'div2')  # Go from K=2 to K=1

    #_temp_flag:
    #    value: 0
    #    csv_use_default: True

    _pres:
        value: get('press_gnss')

    #TODO: is this assignment correct ?
    _pres_uct:
        value: get('press_gnss_uc_repe', 'div2')  # Go from K=2 to K=1

    #TODO: is this assignment correct ?
    _pres_ucu:
        value: get('press_gnss_uc_noise', 'div2')  # Go from K=2 to K=1

    _rh:
        value: get('rh')

    #_rh_ucr:
    #    value: 'rh_uc_ucor'

    _rh_uct:
        value: get('rh_uc', 'div2')  # Go from K=2 to K=1

    _wdir:
        value: get('wdir')

    _wdir_ucu:
        value: get('wdir_uc', 'div2')  # Go from K=2 to K=1

    _wspeed:
        value: get('wspeed')

    _wspeed_ucu:
        value: get('wspeed_uc', 'div2')  # Go from K=2 to K=1
