# ----------------------------------------------------
# SRS-C50 type (NOT THE GDP!)
# ----------------------------------------------------
_C50:

    # -- META DATA ----------------------------------
    edt: "get('event_dt')"
    srn: "get('srn')"
    pid: "get('product_id')"
    tags:
        - "cat('e:', get('event_id'))"
        - "cat('r:', get('rig'))"
        - "get('day_night')"

    # -- ORIG DATA ----------------------------------
    csv_delimiter: ';'
    csv_skip_blank_lines: True
    csv_skiprows: 40
    csv_skipfooter: 1

    _tdtpros1:
        value_col: 0
        lambda: 'lambda x: x * 1E9'

    _trepros1:
        value_col: 5

    _altpros1:
        value_col: 1

    _prepros1:
        value_col: 4


# ----------------------------------------------------
# SRS-C34 type (NOT THE GDP!)
# ----------------------------------------------------
_C34:

    # -- META DATA ----------------------------------

    edt: "get('event_dt')"
    srn: "get('srn')"
    pid: "get('product_id')"
    tags:
        - "cat('e:', get('event_id'))"
        - "cat('r:', get('rig'))"
        - "get('day_night')"

    # -- ORIG DATA ----------------------------------
    csv_delimiter: ';'
    csv_skip_blank_lines: True
    csv_skiprows: 48
    csv_skipfooter: 1

    _tdtpros1:
        value_col: 0
        lambda: 'lambda x: x * 1E9'

    _trepros1:
        value_col: 5

    _altpros1:
        value_col: 1

    _prepros1:
        value_col: 4

# ----------------------------------------------------
# RS-41 type (NOT THE GDP!)
# ----------------------------------------------------
_RS41:

    # -- META DATA ----------------------------------
    edt: "get('event_dt')"
    srn: "get('srn')"
    pid: "get('product_id')"
    tags:
        - "cat('e:', get('event_id'))"
        - "cat('r:', get('rig'))"
        - "get('day_night')"

    # -- ORIG DATA ----------------------------------
    csv_delimiter:
    csv_skip_blank_lines: True
    csv_delim_whitespace: True
    csv_skiprows: 1

    _tdtpros1:
        value_col: 0
        lambda: 'lambda x: x * 1E9'

    _trepros1:
        value_col: 4

    _altpros1:
        value_col: 2

    _prepros1:
        value_col: 3

# ----------------------------------------------------
# RS-92 type (NOT THE GDP!)
# ----------------------------------------------------
_RS92:

    # -- META DATA ----------------------------------
    edt: "get('event_dt')"
    srn: "get('srn')"
    pid: "get('product_id')"
    tags:
        - "cat('e:', get('event_id'))"
        - "cat('r:', get('rig'))"
        - "get('day_night')"
    metadata:
        key_str: '1'
        key_num: 1

    # -- ORIG DATA ----------------------------------
    csv_delimiter:
    csv_skip_blank_lines: True
    csv_delim_whitespace: True
    csv_skiprows: 2

    _tdtpros1:
        value_col: 0
        lambda: 'lambda x: x * 1E9'

    _trepros1:
        value_col: 3

    _altpros1:
        value_col: 1

    _prepros1:
        value_col: 2

    _trepros1_flag:
        value_col: 0
        csv_use_default: True


# ----------------------------------------------------
# RS-41 GDP, version beta-1
# ----------------------------------------------------
_RS41-GDP-BETA_001:

    # -- META DATA ----------------------------------

    edt: "get('g.Measurement.StandardTime')"
    srn: "get('g.MainSonde.SerialNumber')"
    pid: "get('g.Product.ID')"
    tags:
        - "cat('e:', get('g.Measurement.Id'))"
        - "cat('r:', get('g.Measurement.BalloonNumber'))"

    # -- ORIG DATA ----------------------------------
    _tdtpros1:
        value_col: 'time'
        lambda: 'lambda x: x * 1E9'

    _trepros1:
        value_col: 'temp'

    _treprosu_r:
        value_col: 'temp_uc_ncor'

    _treprosu_s:
        value_col: 'temp_uc_scor'

    _treprosu_t:
        value_col: 'temp_uc_tcor'

    _altpros1:
        value_col: 'alt_gph'

    _prepros1:
        value_col: 'press'

    _preprosu_u:
        value_col: 'press_uc'

    _trepros1_flag:
        value_col: 0
        csv_use_default: True


# ----------------------------------------------------
# RS92-GDP, version 2
# ----------------------------------------------------
_RS92-GDP_002:

    # -- META DATA ----------------------------------
    edt: "cat(get('g.Ascent.StandardTime'),'Z')"
    srn: "get('g.Instrument.SerialNumber')"
    pid: "get('g.Product.ID')"
    tags:
        - "cat('e:', get('g.Ascent.ID'))"
        - "cat('r:', get('g.Ascent.BalloonNumber'))"

    # -- ORIG DATA ----------------------------------
    _tdtpros1:
        value_col: 'time'
        lambda: 'lambda x: x * 1E9'

    _trepros1:
        value_col: 'temp'

    _treprosu_r:
        # TODO: in v2 of the GDP, this value is wrong. It must be reconstructed from:
        # value_col: sqrt('u_temp'**2 - 'u_cor_temp'**2)
        value_col: 'u_std_temp'

    _treprosu_t:
        value_col: 'u_cor_temp'

    _altpros1:
        value_col: 'geopot'

    _prepros1:
        value_col: 'press'

    _preprosu_u:
        value_col: 'u_press'
