# ----------------------------------------------------
# SRS-C50 type (NOT THE GDP!)
# ----------------------------------------------------
_C50:

    # -- META DATA ----------------------------------
    edt: "get('event_dt')"
    srn: "get('srn')"
    pid: "get('product_id')"
    tags:
        - "cat('e:', get('event_id'))"
        - "cat('r:', get('rig'))"
        - "get('day_night')"

    # -- ORIG DATA ----------------------------------
    csv_delimiter: ';'
    csv_skip_blank_lines: True
    csv_skiprows: 40
    csv_skipfooter: 1

    _time:
        value_col: 0
        lambda: 'lambda x: x * 1E9'

    _gph:
        value_col: 1

    _temp:
        value_col: 5

    _pres:
        value_col: 4


# ----------------------------------------------------
# SRS-C34 type (NOT THE GDP!)
# ----------------------------------------------------
_C34:

    # -- META DATA ----------------------------------

    edt: "get('event_dt')"
    srn: "get('srn')"
    pid: "get('product_id')"
    tags:
        - "cat('e:', get('event_id'))"
        - "cat('r:', get('rig'))"
        - "get('day_night')"

    # -- ORIG DATA ----------------------------------
    csv_delimiter: ';'
    csv_skip_blank_lines: True
    csv_skiprows: 48
    csv_skipfooter: 1

    _time:
        value_col: 0
        lambda: 'lambda x: x * 1E9'

    _gph:
        value_col: 1

    _temp:
        value_col: 5

    _pres:
        value_col: 4

# ----------------------------------------------------
# RS-41 type (NOT THE GDP!), 2017 file format
# ----------------------------------------------------
_RS41-2017:

    # -- META DATA ----------------------------------
    edt: "get('event_dt')"
    srn: "get('srn')"
    pid: "get('product_id')"
    tags:
        - "cat('e:', get('event_id'))"
        - "cat('r:', get('rig'))"
        - "get('day_night')"

    # -- ORIG DATA ----------------------------------
    csv_delimiter:
    csv_skip_blank_lines: True
    csv_delim_whitespace: True
    csv_skiprows: 1

    _time:
        value_col: 0
        lambda: 'lambda x: x * 1E9'

    _gph:
        value_col: 2

    _temp:
        value_col: 4
        lambda: 'lambda x: x + 273.15'

    _pres:
        value_col: 3

    _rh:
        value_col: 5

# ----------------------------------------------------
# RS-41 type (NOT THE GDP!), latest file format
# ----------------------------------------------------
_RS41:

    # -- META DATA ----------------------------------
    edt: "get('event_dt')"
    srn: "get('srn')"
    pid: "get('product_id')"
    tags:
        - "cat('e:', get('event_id'))"
        - "cat('r:', get('rig'))"
        - "get('day_night')"

    # -- ORIG DATA ----------------------------------
    csv_delimiter: ';'
    csv_skip_blank_lines: True
    csv_delim_whitespace: False
    csv_skiprows: 47

    _time:
        value_col: 0
        lambda: 'lambda x: x * 1E9'

    _gph:
        value_col: 2

    _temp:
        value_col: 4
        lambda: 'lambda x: x + 273.15'

    _pres:
        value_col: 3

    _rh:
        value_col: 5

# ----------------------------------------------------
# RS-92 type (NOT THE GDP!)
# ----------------------------------------------------
_RS92:

    # -- META DATA ----------------------------------
    edt: "get('event_dt')"
    srn: "get('srn')"
    pid: "get('product_id')"
    tags:
        - "cat('e:', get('event_id'))"
        - "cat('r:', get('rig'))"
        - "get('day_night')"
    metadata:
        key_str: '1'
        key_num: 1

    # -- ORIG DATA ----------------------------------
    csv_delimiter:
    csv_skip_blank_lines: True
    csv_delim_whitespace: True
    csv_skiprows: 2

    _time:
        value_col: 0
        lambda: 'lambda x: x * 1E9'

    _gph:
        value_col: 1

    _temp:
        value_col: 3
        lambda: 'lambda x: x + 273.15'

    _temp_flag:
        value_col: 0
        csv_use_default: True

    _pres:
        value_col: 2

    _rh:
        value_col: 4

# ----------------------------------------------------
# M10 type (NOT THE GDP!)
# ----------------------------------------------------
_M10:

    # -- META DATA ----------------------------------
    edt: "get('event_dt')"
    srn: "get('srn')"
    pid: "get('product_id')"
    tags:
        - "cat('e:', get('event_id'))"
        - "cat('r:', get('rig'))"
        - "get('day_night')"

    # -- ORIG DATA ----------------------------------
    csv_delimiter:
    csv_skip_blank_lines: True
    csv_delim_whitespace: True
    csv_skiprows: 1

    _time:
        value_col: 0
        lambda: 'lambda x: x * 1E9'

    _gph:
        value_col: 1

    _temp:
        value_col: 10
        lambda: 'lambda x: x + 273.15'

    _pres:
        value_col: 12

    _rh:
        value_col: 11

# ----------------------------------------------------
# RS-41 GDP, version beta-1
# ----------------------------------------------------
_RS41-GDP-BETA_001:

    # -- META DATA ----------------------------------

    edt: "get('g.Measurement.StandardTime')"
    srn: "get('g.MainSonde.SerialNumber')"
    pid: "get('g.Product.ID')"
    tags:
        - "cat('e:', get('g.Measurement.Id'))"
        - "cat('r:', get('g.Measurement.BalloonNumber'))"

    # -- ORIG DATA ----------------------------------
    _time:
        value_col: 'time'
        lambda: 'lambda x: x * 1E9'

    _gph:
        value_col: 'alt_gph'

    _temp:
        value_col: 'temp'

    _temp_ucr:
        value_col: 'temp_uc_ncor'

    _temp_ucs:
        value_col: 'temp_uc_scor'

    _temp_uct:
        value_col: 'temp_uc_tcor'

    _temp_flag:
        value_col: 0
        csv_use_default: True

    _pres:
        value_col: 'press_gnss'

    _pres_uct:
        value_col: 'press_gnss_uc'

    _wdir:
        value_col: 'wdir'

    _wdir_ucu:
        value_col: 'wdir_uc'

    _wspeed:
        value_col: 'wspeed'

    _wspeed_ucu:
        value_col: 'wspeed_uc'

# ----------------------------------------------------
# RS-41 GDP, version beta-2
# ----------------------------------------------------
_RS41-GDP-BETA_002:

    # -- META DATA ----------------------------------

    edt: "get('g.Measurement.StandardTime')"
    srn: "get('g.MainSonde.SerialNumber')"
    pid: "get('g.Product.Id')"
    tags:
        - "cat('e:', get('g.Measurement.Id'))"
        - "cat('r:', get('g.Measurement.BalloonNumber'))"

    # -- ORIG DATA ----------------------------------
    _time:
        value_col: 'time'
        lambda: 'lambda x: x * 1E9'

    _gph:
        value_col: 'alt_gph'

    _gph_uct:
        value_col: 'alt_gph_uc_tcor'

    _gph_ucu:
        value_col: 'alt_gph_uc_ucor'

    _temp:
        value_col: 'temp'

    _temp_ucr:
        value_col: 'temp_uc_ucor'

    _temp_ucs:
        value_col: 'temp_uc_scor'

    _temp_uct:
        value_col: 'temp_uc_tcor'

    _temp_flag:
        value_col: 0
        csv_use_default: True

    _pres:
        value_col: 'press_gnss'

    _pres_uct:
        value_col: 'press_gnss_uc_tcor'

    _pres_ucu:
        value_col: 'press_gnss_uc_ucor'

    _rh:
        value_col: 'rh'

    _rh_ucr:
        value_col: 'rh_uc_ucor'

    _rh_uct:
        value_col: 'rh_uc_tcor'

    _wdir:
        value_col: 'wdir'

    _wdir_ucu:
        value_col: 'wdir_uc'

    _wspeed:
        value_col: 'wspeed'

    _wspeed_ucu:
        value_col: 'wspeed_uc'

# ----------------------------------------------------
# RS92-GDP, version 2
# ----------------------------------------------------
_RS92-GDP_002:

    # -- META DATA ----------------------------------
    edt: "cat(get('g.Ascent.StandardTime'),'Z')"
    srn: "get('g.Instrument.SerialNumber')"
    pid: "get('g.Product.ID')"
    tags:
        - "cat('e:', get('g.Ascent.ID'))"
        - "cat('r:', get('g.Ascent.BalloonNumber'))"

    # -- ORIG DATA ----------------------------------
    _time:
        value_col: 'time'
        lambda: 'lambda x: x * 1E9'

    _gph:
        value_col: 'geopot'

    _temp:
        value_col: 'temp'

    _temp_ucr:
        # TODO: in v2 of the GDP, this value is wrong. It must be reconstructed from:
        # value_col: sqrt('u_temp'**2 - 'u_cor_temp'**2)
        value_col: 'u_std_temp'

    _temp_uct:
        value_col: 'u_cor_temp'

    _pres:
        value_col: 'press'

    _pres_uct:
        value_col: 'u_press'

    _rh:
        value_col: 'rh'

    _rh_ucr:
        # TODO: this needs to be checked. Is it as wrong as the temperature ?
        value_col: 'u_std_rh'

    _rh_uct:
        value_col: 'u_cor_rh'

    _wdir:
        value_col: 'wdir'

    _wdir_ucu:
        value_col: 'u_wdir'

    _wspeed:
        value_col: 'wspeed'

    _wspeed_ucu:
        value_col: 'u_wspeed'
