# Parameter configuration file

- prm_name: 'time'
  prm_desc: 'Time'
  prm_unit: 's'

- prm_name: 'gph'
  prm_desc: 'Geopotential height'
  prm_unit: 'm'

- prm_name: 'temp(|(_ucr)|(_ucs)|(_uct)|(_ucu))'
  # Generate variables from regex generator for temperature.
  prm_desc: 'cat("Temperature", repl({"_ucr": " rig-correlated uncertainty",
                                      "_ucs": " spatial-correlated uncertainty",
                                      "_uct": " temporal-correlated uncertainty",
                                      "_ucu": " un-correlated uncertainty"}, get(1)))'
  prm_unit: 'degC'

- prm_name: 'rh(|(_uct)|(_ucu))'
  # Generate variables from regex generator for relative humidity.
  prm_desc: 'cat("Relative humidity", repl({"_uct": " temporal-correlated uncertainty",
                                            "_ucu": " un-correlated uncertainty"}, get(1)))'
  prm_unit: '%'

- prm_name: '(pres|alt)(|(_uct))'
  # Generate variables from regex generator for pressure.
  prm_desc: 'cat(repls({"pres": "Pressure",
                        "alt": "Altitude a.m.s.l."}, get(1)),
                 repl({"_uct": " temporal-correlated uncertainty"}, get(2)))'
  prm_unit: 'repls({"pres": "hPa",
                    "alt": "m"}, get(1))'

- prm_name: '(wdir|wspeed)(|(_ucu))'
  # Generate variables from regex generator for wind direction.
  prm_desc: 'cat(repls({"wdir": "Wind direction",
                        "wspeed": "Wind speed"}, get(1)),
                 repl({"_ucu": " un-correlated uncertainty"}, get(2)))'
  prm_unit: 'repls({"wdir": "deg",
                    "wspeed": "m/s"}, get(1))'
