
- tag_name: 'e:((\d{1,2})|(805\d{2})|(806\d{2})|(1391\d{2})|(1399\d{2}))'
  # Generate e1, e2, ..., e99,...
  tag_desc: "cat('Event', ' ', get(1))"
  # Use standard re.sub group syntax to refer group number from regexp
  # generator.

- tag_name: 'r:([12])'
  # Generate r1, r2
  tag_desc: "cat('Rig', ' ', get(1))"

- tag_name: 'p:(\d)'
  # Generate p0, p1,...
  tag_desc: "cat('Product', ' ', get(1))"

- tag_name: '^((day)|(night))'
  # Generate day, night
  # In this example, '^' is required at the beginning to
  # create regexp groups almost no group will be catch.
  tag_desc: "cat(supper(get(1)), ' ', 'event')"
  # Use lambda function to set 1st character to upper case and append the rest
  # of the group in lower case.
