
- mdl_name: 'RS41-GDP_001'
  mdl_desc: 'RS41 GDP, version 1'
  mid: 'RS41-GDP'

- mdl_name: 'RS92-GDP_002'
  mdl_desc: 'RS92 GDP, version 2'
  mid: 'RS92-GDP'

- mdl_name: 'M10-GDP-ALPHA_002'
  mdl_desc: 'M10, ALPHA version 2'
  mid: 'M10-GDP'
