# Copyright (c) 2020-2022 MeteoSwiss, contributors listed in AUTHORS.
#
# Distributed under the terms of the GNU General Public License v3.0 or later.
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This file contains the extraction details for the iMet-54 MDP files.
# It must absolutely have the string 'origdata' in its name, to match the dvas class names.
# --------------------------------------------------------------------------------------------------

# ----------------------------------------------------
# iMet-54 MDP (UAII2022)
# ----------------------------------------------------
_iMet-54:

    # -- META DATA ----------------------------------
    edt: "to_datetime(get('event_dt'))"
    srn: "get('srn')"
    pid: "get('product_id')"
    tags:
        - "cat('e:', get('event_id'))"
        - "cat('r:', get('rig_id'))"
    metadata:
        first_timestamp: "to_datetime(get('first_timestamp'))"
        launch_timestamp: "to_datetime(get('launch_timestamp'))"
        burst_timestamp: "to_datetime(get('burst_timestamp'))"
        preflight_shc_rh_sonde: "get('preflight_SHC_rh_sonde')"
        preflight_shc_rh_ref: "get('preflight_SHC_rh_ref')"
        preflight_shc_temp_sonde: "get('preflight_SHC_temp_sonde')"
        preflight_shc_temp_ref: "get('preflight_SHC_temp_ref')"

    # -- ORIG DATA ----------------------------------
    csv_delimiter: ';'
    csv_skip_blank_lines: False
    csv_delim_whitespace: False
    csv_skiprows: 21
    csv_skipfooter: 0
    csv_encoding:
    csv_na_values:
    csv_header: 0

    _time:
        value: get('time', 'rel')

    _alt_ref:
        value: get('gph_gnss')

    _gph:
        value: get('gph_gnss')

    _temp:
        value: get('temp', 'c2k')

    _pres:
        value: get('press_gnss')

    _rh:
        value: get('rh')

    _wdir:
        value: get('wind_dir')

    _wspeed:
        value: get('wind_speed')
