
_RS92-GDP_002:

    # -- META DATA ----------------------------------
    dt_field: '{g.Ascent.StandardTime}Z'
    sn_field: '{g.Instrument.SerialNumber}'
    tag_field:
        - 'b{g.Ascent.BalloonNumber}'
        - 'e{g.Ascent.ID}'

    # -- ORIG DATA ----------------------------------
    index_unit: 's'
    index_col: 'time'

    _trepros1:
        value_col: 'temp'
        lambda: 'lambda x: x - 273.15'

    _treprosu:
        value_col: 'u_temp'

    _prepros1:
        value_col: 'press'


_RS41-GDP-BETA_001:

    # -- META DATA ----------------------------------
    dt_field: '{g.Measurement.StandardTime}'
    sn_field: '{g.MainSonde.SerialNumber}'
    tag_field:
        - 'b{g.Measurement.BalloonNumber}'
        - 'e{g.Measurement.Id}'

    # -- ORIG DATA ----------------------------------
    index_unit: 's'
    index_col: 'time'

    _trepros1:
        value_col: 'temp'
        lambda: 'lambda x: x - 273.15'
