_vai-rs92:
    idx_unit: 's'
    delimiter:
    delim_whitespace: True
    header: 1
    skiprows: 1

    _altpros1:
        usecols:
            - 0
            - 1

    _prepros1:
        usecols:
            - 0
            - 2

    _trepros1:
        usecols:
            - 0
            - 3




_vai-rs41:
    idx_unit: 's'
    delimiter: ';'
    skiprows: 1
    header: 1

    _trepros1:
        usecols:
            - 0
            - 4

    _altpros1:
        usecols:
            - 0
            - 2

    _prepros1:
        usecols:
            - 0
            - 3


_metlab-c34:
    idx_unit: 's'
    delimiter: ';'
    skiprows: 1
    header: 0

    _altpros1:
        usecols:
            - 0
            - 1

    _prepros1:
        usecols:
            - 0
            - 4

    _trepros1:
        usecols:
            - 0
            - 5

_metlab-c50:
    idx_unit: 's'
    delimiter: ';'
    skiprows: 0
    header: 0

    _altpros1:
        usecols:
            - 0
            - 3

    _fklpros1:
        usecols:
            - 0
            - 5

    _prepros1:
        usecols:
            - 0
            - 6

    _trepros1:
        usecols:
            - 0
            - 7
