# Parameter configuration file

- prm_abbr: 'trepros1'
  prm_desc: 'Temperature'

- prm_abbr: 'urepros1'
  prm_desc: 'Relative humidity'

- prm_abbr: 'prepros1'
  prm_desc: 'Pressure'

- prm_abbr: 'altpros1'
  prm_desc: 'Altitude'

- prm_abbr: 'fklpros1'
  prm_desc: 'Wind speed'

- prm_abbr: 'dklpros1'
  prm_desc: 'Wind direction'

- prm_abbr: 'treprosu'
  prm_desc: 'Temperature uncertainty'

- 'prm_abbr': 'ureprosu'
  'prm_desc': 'Humidity uncertainty'

- 'prm_abbr': 'preprosu'
  'prm_desc': 'Pressure uncertainty'

- 'prm_abbr': 'altprosu'
  'prm_desc': 'Altitude uncertainty'

- 'prm_abbr': 'fklprosu'
  'prm_desc': 'Wind speed uncertainty'

- 'prm_abbr': 'dklprosu'
  'prm_desc': 'Wind direction uncertainty'
