# Copyright (c) 2020-2022 MeteoSwiss, contributors listed in AUTHORS.
#
# Distributed under the terms of the GNU General Public License v3.0 or later.
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This file contains the extraction details for the ATMS-3710 MDP files.
# It must absolutely have the string 'origdata' in its name, to match the dvas class names.
# --------------------------------------------------------------------------------------------------

# ----------------------------------------------------
# ATMS-3710 MDP (UAII2022)
# ----------------------------------------------------
_ATMS-3710:

    # -- META DATA ----------------------------------
    edt: "to_datetime(get('event_dt'))"
    srn: "get('srn')"
    pid: "get('product_id')"
    tags:
        - "cat('e:', get('event_id'))"
        - "cat('r:', get('rig'))"
    metadata:
        bpt_time:
        start_time: "to_datetime(get('start_time'))"

    # -- ORIG DATA ----------------------------------
    csv_delimiter: ';'
    csv_skip_blank_lines: False
    csv_delim_whitespace: False
    csv_skiprows: 18
    csv_skipfooter: 0
    csv_encoding:
    csv_na_values:
    csv_header: 0

    _time:
        value: getreldt('time_stamp', '%Y-%m-%dT%H:%M:%S.%fz')

    _alt_ref:
        value: get('gph_gnss')

    _gph:
        value: get('gph_gnss')

    _temp:
        value: get('temp_air', 'c2k')

    _pres:
        value: get('press_sens')

    _rh:
        value: get('rh')

    _wdir:
        value: get('wind_dir')

    _wspeed:
        value: get('wind_speed')
