# Copyright (c) 2020-2022 MeteoSwiss, contributors listed in AUTHORS.
#
# Distributed under the terms of the GNU General Public License v3.0 or later.
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This file contains the extraction details for M10 GDP and MDP files.
# It must absolutely have the string 'origdata' in its name, to match the dvas class names.
# --------------------------------------------------------------------------------------------------

# ----------------------------------------------------
# M10 MDP (default)
# ----------------------------------------------------
_M10:

    # -- META DATA ----------------------------------
    edt: "to_datetime(get('event_dt'))"
    srn: "get('srn')"
    pid: "get('product_id')"
    tags:
        - "cat('e:', get('event_id'))"
        - "cat('r:', get('rig_id'))"
    metadata:
        first_timestamp: "to_datetime(get('first_timestamp'))"
        launch_timestamp: "to_datetime(get('launch_timestamp'))"
        burst_timestamp: "to_datetime(get('burst_timestamp'))"

    # -- ORIG DATA ----------------------------------
    csv_delimiter:
    csv_skip_blank_lines: False
    csv_delim_whitespace: True
    csv_skiprows: 0
    csv_skipfooter: 0
    csv_encoding:
    csv_na_values:
    csv_header: 0

    _time:
        value: get('Time', 'rel')

    _alt_ref:
        value: get('Altitude')

    _gph:
        value: get('Altitude')

    _temp:
        value: get('T', 'c2k')

    _pres:
        value: get('Press')

    _rh:
        value: get('U')

    _wdir:
        value: get('WindD')

    _wspeed:
        value: get('WindF')
