# Copyright (c) 2020-2023 MeteoSwiss, contributors listed in AUTHORS.
#
# Distributed under the terms of the GNU General Public License v3.0 or later.
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This file contains the extraction details for RS41 GDP and MDP files.
# It must absolutely have the string 'origdata' in its name, to match the dvas class names.
# --------------------------------------------------------------------------------------------------

# ----------------------------------------------------
# RS41 MDP (MCH pre-2018 format)
# ----------------------------------------------------
_RS41-MCH-PRE2018:

    # -- META DATA ----------------------------------
    edt: "to_datetime(get('event_dt'))"
    srn: "get('srn')"
    pid: "get('product_id')"
    tags:
        - "cat('e:', get('event_id'))"
        - "cat('r:', get('rig_id'))"
    metadata:
        first_timestamp: "to_datetime(get('first_timestamp'))"
        launch_timestamp: "to_datetime(get('launch_timestamp'))"
        burst_timestamp: "to_datetime(get('burst_timestamp'))"

    # -- ORIG DATA ----------------------------------
    csv_delimiter:
    csv_skip_blank_lines: True
    csv_delim_whitespace: True
    csv_skiprows: 1
    csv_skipfooter: 0
    csv_encoding: 'utf_8'
    csv_na_values:

    _time:
        value: get(0)

    _alt_ref:
        value: get(2)

    _gph:
        value: get(2)

    _temp:
        value: get(4, 'c2k')

    _pres:
        value: get(3)

    _rh:
        value: get(5)

    _wdir:
        value: get(6)

    _wspeed:
        value: get(7)

# ----------------------------------------------------
# RS41 MDP (MCH current format)
# ----------------------------------------------------
_RS41-MCH:

    # -- META DATA ----------------------------------
    edt: "to_datetime(get('event_dt'))"
    srn: "get('srn')"
    pid: "get('g.GroundSystem.SerialNumber')"
    tags:
        - "cat('e:', get('event_id'))"
        - "cat('r:', get('rig_id'))"
    metadata:
        first_timestamp: "to_datetime(get('first_timestamp'))"
        launch_timestamp: "to_datetime(get('launch_timestamp'))"
        burst_timestamp: "to_datetime(get('burst_timestamp'))"

    # -- ORIG DATA ----------------------------------
    csv_delimiter: ';'
    csv_skip_blank_lines: False
    csv_delim_whitespace: False
    csv_skiprows: 'lambda x: ((x<=45) or (x==47))'
    csv_skipfooter: 0
    csv_encoding: 'latin_1'
    csv_na_values: '//////'
    csv_header: 0

    _time:
        value: get('Elapsed time')

    _alt_ref:
        value: get('GpsHeightMSL')

    _gph:
        value: get('GpsHeightMSL')

    _temp:
        value: get('Temp', 'c2k')

    _pres:
        value: get('P')

    _rh:
        value: get('RH')

    _wdir:
        value: get('Dir')

    _wspeed:
        value: get('Speed')

# ----------------------------------------------------
# RS41 MDP (UAII2022)
# ----------------------------------------------------
_RS41:

    # -- META DATA ----------------------------------
    edt: "to_datetime(get('event_dt'))"
    srn: "get('srn')"
    pid: "get('product_id')"
    tags:
        - "cat('e:', get('event_id'))"
        - "cat('r:', get('rig_id'))"
    metadata:
        first_timestamp: "to_datetime(get('first_timestamp'))"
        launch_timestamp: "to_datetime(get('launch_timestamp'))"
        burst_timestamp: "to_datetime(get('burst_timestamp'))"
        preflight_shc_rh_sonde: "get('preflight_SHC_rh_sonde')"
        preflight_shc_rh_ref: "get('preflight_SHC_rh_ref')"
        preflight_shc_temp_sonde: "get('preflight_SHC_temp_sonde')"
        preflight_shc_temp_ref: "get('preflight_SHC_temp_ref')"

    # -- ORIG DATA ----------------------------------
    csv_delimiter: ';'
    csv_skip_blank_lines: False
    csv_delim_whitespace: False
    csv_skiprows: 18
    csv_skipfooter: 0
    csv_encoding:
    csv_na_values: 'NaN'
    csv_header: 0

    _time:
        value: getreldt('time_stamp', '%Y-%m-%dT%H:%M:%S.%fZ', 0)

    _alt_ref:
        value: get('gph_gnss')

    _gph:
        value: get('gph_gnss')

    _temp:
        value: get('temp_air', 'c2k')

    _pres:
        value: get('press_gnss')

    _rh:
        value: get('rh')

    _wdir:
        value: get('wind_dir')

    _wspeed:
        value: get('wind_speed')

# ----------------------------------------------------
# RS41 GDP, version 1
# ----------------------------------------------------
_RS41-GDP_001:

    # -- META DATA ----------------------------------

    edt: "to_datetime(get('g.Measurement.StandardTime'))"
    srn: "get('g.MainSonde.SerialNumber')"
    pid: "get('g.Product.Id')"
    tags:
        - "cat('e:', get('g.Measurement.Id'))"
        - "cat('r:', get('g.Measurement.BalloonNumber'))"
        - "cat('tod:', get('g.Measurement.TimeOfDay'))"
    metadata:
        first_timestamp: "to_datetime(get('g.Measurement.StartTime'))"
        launch_timestamp: "to_datetime(get('g.Measurement.StartTime'))"
        burst_timestamp: "to_datetime(get('g.Measurement.BurstpointDatetime'))"
        gruan_tropopause: "get('g.Measurement.TropopauseGeopotHeight')"
        synop_clouds: "get('g.SurfaceObs.SynopClouds')"
        preflight_shc_rh_sonde: "get('g.GroundCheck.SHC.SensorRelativeHumidity')"
        preflight_shc_rh_ref: "get('g.GroundCheck.SHC.RefRelativeHumidity')"
        preflight_shc_temp_sonde: "get('g.GroundCheck.SHC.SensorTemperature')"
        preflight_shc_temp_ref: "get('g.GroundCheck.SHC.RefTemperature')"

    # -- ORIG DATA ----------------------------------
    _time:
        value: get('time')

    _alt_ref:
        value: get('alt_gph')

    _gph:
        value: get('alt_gph')
    _gph_uct:
        value: get('alt_gph_uc_tcor', 'div2')  # Go from K=2 to K=1
    _gph_ucu:
        value: get('alt_gph_uc_ucor', 'div2')  # Go from K=2 to K=1

    _temp:
        value: get('temp')
    _temp_ucs:
        value: get('temp_uc_scor', 'div2')  # Go from K=2 to K=1
    _temp_uct:
        value: get('temp_uc_tcor', 'div2')  # Go from K=2 to K=1
    _temp_ucu:
        value: get('temp_uc_ucor', 'div2')  # Go from K=2 to K=1
    # What follows illustrates how one could feed manual flags via a .flg CSV file.
    #_temp_flag:
    #    value: get(0)
    #    csv_use_default: True

    _pres:
        value: get('press_gnss')
    _pres_uct:
        value: get('press_gnss_uc_tcor', 'div2')  # Go from K=2 to K=1
    _pres_ucu:
        value: get('press_gnss_uc_ucor', 'div2')  # Go from K=2 to K=1

    _rh:
        value: get('rh')
    _rh_uct:
        value: get('rh_uc_tcor', 'div2')  # Go from K=2 to K=1
    _rh_ucu:
        value: get('rh_uc_ucor', 'div2')  # Go from K=2 to K=1

    _wdir:
        value: get('wdir')
    _wdir_ucu:
        value: get('wdir_uc_ucor', 'div2')  # Go from K=2 to K=1

    _wspeed:
        value: get('wspeed')
    _wspeed_ucu:
        value: get('wspeed_uc_ucor', 'div2')  # Go from K=2 to K=1

    _lat:
        value: get('lat')

    _lon:
        value: get('lon')
