# Copyright (c) 2020-2022 MeteoSwiss, contributors listed in AUTHORS.
#
# Distributed under the terms of the GNU General Public License v3.0 or later.
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This file contains the extraction details for SRS-C50 GDP and MDP files.
# It must absolutely have the string 'origdata' in its name, to match the dvas class names.
# --------------------------------------------------------------------------------------------------


# ----------------------------------------------------
# SRS-C50 MDP
# ----------------------------------------------------
_C50:

    # -- META DATA ----------------------------------
    edt: "to_datetime(get('event_dt'))"
    srn: "get('srn')"
    pid: "get('product_id')"
    tags:
        - "cat('e:', get('event_id'))"
        - "cat('r:', get('rig'))"
        - "get('day_night')"
    metadata:
        bpt_time: "get('bpt_time')"
        start_time: "to_datetime(get('start_time'))"

    # -- ORIG DATA ----------------------------------
    csv_delimiter: ';'
    csv_skip_blank_lines: False
    csv_delim_whitespace: False
    csv_skiprows: 40
    csv_skipfooter: 1
    csv_encoding:
    csv_na_values:
    csv_header: 0

    _time:
        value: get('Rel. Time')

    _alt_ref:
        value: get('Altitude (gpm)')

    _gph:
        value: get('Altitude (gpm)')

    _temp:
        value: get('Temperature (?C)', 'd2k')

    _rh:
        value: get('Humidity (%)')

    _pres:
        value: get('Pressure (hPa)')

    _wdir:
        value: get('Wind Direction (?)')

    _wspeed:
        value: get('Wind Velocity (m/s)')
