# This Actions checks if the CHANGELOG was modified. If not, raises an error.
#
# Created May 2020; F.P.A. Vogt; frederic.vogt@alumni.anu.edu.au

name: CI_changelog

on:
  pull_request:
    branches: [ master, develop ]

jobs:
  changelog:

    runs-on: ubuntu-latest
    steps:
      # Checkout our repository
      - uses: actions/checkout@v2 

      # Set up Python
      - uses: actions/setup-python@v1

      - name: Check if changelog was modified
        run: |
           python ./.github/workflows/fmod_checker.py --filename CHANGELOG