# This workflow will install Python dependencies and run tests with a variety of Python
# versions. For more information see:
# https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
# Adapted from: https://github.com/actions/starter-workflows/blob/master/ci/python-package.yml
#
# Copyright (c) 2020-2023 MeteoSwiss, created by F.P.A. Vogt; frederic.vogt@meteoswiss.ch

name: CI_pytest

on:
  # Not required on push: no code should go to master directly.
  #push:
  #  branches: [ master ]
  pull_request:
    branches: [ master, develop ]

jobs:
  pytest:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.11']

    steps:
    # Checkout the repository
    - name: Checkout current repository
      uses: actions/checkout@v4

    # Setup python
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    # Here, let's install our module to make sure all the dependencies specified in setup.py are
    # also installed
    - name: Install our module
      run: pip install -e .[dev]

    # Read to run all the tests !
    - name: Test dvas with pytest
      run: |
        pytest -s
