# This workflow will install Python dependencies and run the dvas demon script.
#
# Copyright (c) 2020-2022 MeteoSwiss, created by F.P.A. Vogt; frederic.vogt@meteoswiss.ch

name: CI_run_demo-script

on:
  # Not required on push: no code should go to master directly.
  #push:
  #  branches: [ master ]
  pull_request:
    branches: [ master, develop ]

jobs:
  demo-script:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
    # Checkout the repository
    - name: Checkout current repository
      uses: actions/checkout@v2

    # Setup python
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip

    # Here, let's install our module to make sure all the dependencies specified in setup.py are
    # also installed
    - name: Install our module
      run: pip install -e .

    # Execute the demo script.
    - name: Execute the dvas demo script
      run: |
        cd src/dvas_demo
        python demo_script.py
